### ISSUE TITLE
Minimum recording implementation

### ISSUE THREAD

**Issue by atimin** [reductstore/ros2_reduct_agent#3]
## Behavior

The agent subscribes to the configured ROS topics, packs received data  into a mcap file on disc and then sends to RedictStore. The mcap file has only  A user can split the ROS topics between the recorded files and send data in different ReductStore entries. 

## Configuration

```yaml

recorder:
  storage:
    url: "http://localhost:8383"   # local ReductStore instance
    api_token: "access_token"
    bucket: "ros-data"

   pipelines:
     telemetry:   # used a entry names
       include_topics:
        - /odom
        - /cmd_vel
        - /imu/data
        - /battery_state
        - /mission_info
      split:
        max_duration_s: 300              # cut files at 5 min or…
        max_size_bytes: 250_000_000      # …≈250 MB, whichever comes first
    camera_preview:
      include_topics:
        - /camera/* # wild-card
      split:
        max_duration_s: 300              # cut files at 5 min or…
        max_size_bytes: 250_000_000      # …≈250 MB, whichever comes first

```
